flowchart TD
    subgraph ably [Ably]
        step2[Ably app]
    end
    subgraph azure [Azure Static Web Apps]
        step1[Vue3 application]-->step3
        step3[NodeJS Azure Function]-->step2
    end
    step1 <--channel--> step2