flowchart TD
    subgraph ably [Ably]
        step2[Ably app]
    end
    subgraph azure [Azure Static Web Apps]
        step1[Vue.js application]-->step3
        step3[Node.js Azure Function]-->step2
    end
    step1 <--channel--> step2