sequenceDiagram
    Client->>Vuex: selectCard(cardNumber)
    activate Client
    activate Vuex
    Vuex->>Vuex: doVote(cardNumber)
    Vuex->>Vuex: addParticipantVoted(vote)
    Vuex->>Ably: publish(vote)
    activate Ably
    Ably->>Other Clients: broadcast: vote
    deactivate Ably
    Client->>Vuex: getVoteCountForCard(cardNumber)
    Vuex-->>Client: count
    Client->>Vuex: getNrOfParticipantsVoted()
    Vuex-->>Client: count
    deactivate Vuex